services:
  - type: web
    name: primeiroamorconecta
    env: node
    plan: free
    buildCommand: |
      cd frontend && npm install && npm run build
      cd ../backend && npm install
    startCommand: node backend/server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        value: supersecreta123
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
